version: "3.8"
services:
  postgres:
    image: postgis/postgis 
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: smart
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

  postgraphile:
    image: dzynetech/smart-postgraphile:$TAG
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - JWT_SECRET
    depends_on:
      - postgres
   
  ingest:
    image: dzynetech/smart-ingest:$TAG
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
    volumes: 
      - ./data:/data:z
    depends_on:
      - postgres

  moviegen:
    image: dzynetech/smart-moviegen:$TAG
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - RDWATCH_HOST
      - RDWATCH_USERNAME
      - RDWATCH_PASSWORD
    volumes: 
      - ./data:/data:z
    depends_on:
      - postgres

  geocode:
    image: dzynetech/smart-geocode:$TAG
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - GEOCODIO_API_KEY
    depends_on:
      - postgres

  nginx:
    image: dzynetech/smart-ui:$TAG
    ports:
      - "$UI_PORT:80"
    depends_on:
      - postgraphile
    volumes:
      - ./data:/usr/share/nginx/html/data:z
      - ./frontend/nginx/logs:/var/log/nginx
      - ./letsencrypt:/etc/letsencrypt/

  pgbackups:
    container_name: postgres_backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - postgres:postgres
    depends_on:
      - postgres 
    environment:
      - POSTGRES_HOST=$DB_HOST
      - POSTGRES_EXTRA_OPTS=-Z9 --blobs
      - SCHEDULE=@every 6h00m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=12
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=80

volumes:
  pgdata:
