version: "3.8"
services:
  postgres:
    image: postgis/postgis 
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: smart
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

  node:
    image: dzynetech/smart-node:develop
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - JWT_SECRET
    depends_on:
      - postgres
   
  ingest:
    image: dzynetech/smart-ingest:develop
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
    depends_on:
      - postgres

  geocode:
    image: dzynetech/smart-geocode:develop
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - GEOCODIO_API_KEY
    depends_on:
      - postgres

  nginx:
    image: dzynetech/smart-ui:develop
    ports:
      - "80:80"
     #- "4180:443"
    depends_on:
      - node 
    volumes:
      - ./data:/usr/share/nginx/html/data
      - ./frontend/nginx/logs:/var/log/nginx
      - ./letsencrypt:/etc/letsencrypt/

  pgbackups:
    container_name: postgres_backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - postgres:postgres
    ports:
      - '4186:8081'
    depends_on:
      - postgres 
    environment:
      - POSTGRES_HOST=$DB_HOST
      - POSTGRES_EXTRA_OPTS=-Z9 --blobs
      - SCHEDULE=@every 6h00m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=12
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8081

volumes:
  pgdata:
