version: "3.8"
services:
  postgres:
    image: postgis/postgis 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart
    ports: 
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  node:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'
        
volumes:
  pgdata: