version: "3.8"
services:
  postgres:
    image: postgis/postgis 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart
    ports: # switch to expose in production
      - '5432:5432' 
    volumes:
      - pgdata:/var/lib/postgresql/data

  node:
    build:
      context: ./node
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
  
  python:
    build:
      context: ./python
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    volumes: 
      - ./python:/app
      
volumes:
  pgdata: