version: "3.8"
services:
  postgres:
    image: postgis/postgis 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart
    ports: 
      - '5432:5432' 
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

  node:
    build:
      context: ./node
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      HTTP_USERNAME: admin
      HTTP_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
      - ./data:/data
  
  ingest:
    build:
      context: ./python/ingest_server
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "4199:4199"

  geocode:
    build:
      context: ./python/geocode
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres

  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:3000"
    depends_on:
      - node
    environment:
      REACT_APP_GRAPHQL_URL: http://localhost:3000/graphql
    volumes:
      - ./frontend/react:/app
      - ./data:/app/public/data
volumes:
  pgdata:
