version: "3.8"
services:
  postgres:
    image: postgis/postgis 
    env_file:
      - secrets
    expose: 
      - '5432' 
    volumes:
      - pgdata:/var/lib/postgresql/data

  node:
    build:
      context: ./node
    env_file:
      - secrets
    depends_on:
      - postgres
    ports:
      - '4401:3000'
  
  python:
    build:
      context: ./python
    env_file:
      - secrets
    depends_on:
      - postgres
      
volumes:
  pgdata: