version: "3.8"
services:
  postgres:
    image: postgis/postgis 
    env_file:
      - secrets
    ports: 
      - '5432:5432' 
    #expose: 
    #  - '5432' 
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

  node:
    build:
      context: ./node
    env_file:
      - secrets
    depends_on:
      - postgres
    volumes:
     - ./node/frontend:/usr/src/app/frontend
     - /data:/data

  python:
    build:
      context: ./python
    env_file:
      - secrets
    depends_on:
      - postgres

  frontend:
    build: 
      context: ./frontend
    ports:
      - "4401:80"
    depends_on:
      - node 

  pgbackups:
    container_name: postgres_backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - postgres:postgres
    ports:
      - '8081:8081'
    depends_on:
      - postgres 
    env_file:
      - secrets
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@every 6h00m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8081

volumes:
  pgdata:
