version: "3.8"
services:
  postgres:
    image: postgis/postgis 
    env_file:
      - secrets
    ports: 
      - '5432:5432' 
    #expose: 
    #  - '5432' 
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

  node:
    build:
      context: ./node
    env_file:
      - secrets
    depends_on:
      - postgres
    ports:
      - '4401:3000'
    volumes:
     - ./node/frontend:/usr/src/app/frontend
     - /data:/data

  python:
    build:
      context: ./python
    env_file:
      - secrets
    depends_on:
      - postgres
      
volumes:
  pgdata:
