version: "3.8"
services:
  postgres:
    image: postgis/postgis 
    env-file:
      -.secrets
    expose: 
      - '5432' 
    volumes:
      - pgdata:/var/lib/postgresql/data

  node:
    build:
      context: ./node
    env-file:
      -.secrets
    depends_on:
      - postgres
    ports:
      - '4401:3000'
    volumes: 
      - ./node:/usr/src/app
  
  python:
    build:
      context: ./python
    env-file:
      -.secrets
    depends_on:
      - postgres
    volumes: 
      - ./python:/app
      
volumes:
  pgdata: