version: "3.8"
services:
  postgres:
    image: postgis/postgis 
    env_file:
      - secrets
    ports: 
      - '5433:5432' 
    #expose: 
    #  - '5432' 
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

  node:
    build:
      context: ./node
    env_file:
      - secrets
    depends_on:
      - postgres
   
  python:
    build:
      context: ./python
    env_file:
      - secrets
    depends_on:
      - postgres

  nginx:
    build: 
      context: ./frontend
    ports:
      - "5000:80"
    depends_on:
      - node 
    volumes:
      - ./data:/usr/share/nginx/html/data
      - ./frontend/nginx/logs:/var/log/nginx
    
  goaccess:
    image: nginx
    ports:
      - "5500:80"
    volumes:
      - ./goaccess/html:/usr/share/nginx/html
      - ./goaccess/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./goaccess/nginx/htpasswd:/etc/nginx/.htpasswd

  # pgbackups:
  #   container_name: postgres_backup
  #   image: prodrigestivill/postgres-backup-local
  #   restart: always
  #   volumes:
  #     - ./backup:/backups
  #   links:
  #     - postgres:postgres
  #   ports:
  #     - '8081:8081'
  #   depends_on:
  #     - postgres 
  #   env_file:
  #     - secrets
  #   environment:
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
  #     - SCHEDULE=@every 6h00m00s
  #     - BACKUP_KEEP_DAYS=7
  #     - BACKUP_KEEP_WEEKS=4
  #     - BACKUP_KEEP_MONTHS=6
  #     - HEALTHCHECK_PORT=8081

volumes:
  pgdata:
