export const colorMap = {
  UNCLASSIFIED: "#FFFFFF",
  CONSTRUCTION: "#CCFFCC",
  NOT_CONSTRUCTION: "#FFCCCC",
  POSSIBLE_CONSTRUCTION: "#FFFF99",
  DUPLICATE: "#FFCCCC",
  HIGHLIGHT: "#EEEEEE",
};

export const borderColorMap = {
  UNCLASSIFIED: "#EEE",
  CONSTRUCTION: " #00CC00",
  NOT_CONSTRUCTION: "#FF0000",
  POSSIBLE_CONSTRUCTION: "#DDDD00",
  DUPLICATE: "#FF0000",
};
