name: Build Docker Images
on: 
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Build Push Node"
        uses: docker/build-push-action@v3
        with:
          context: node
          push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' }}
          tags: dzynetech/smart-node:${{ github.ref_name }}
        timeout-minutes: 240
      - name: "Build Push Ingest"
        uses: docker/build-push-action@v3
        with:
          context: python/ingest_server
          push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' }}
          tags: dzynetech/smart-ingest:${{ github.ref_name }}
        timeout-minutes: 240
      - name: "Build Push Geocode"
        uses: docker/build-push-action@v3
        with:
          context: python/geocode
          push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' }}
          tags: dzynetech/smart-geocode:${{ github.ref_name }}
        timeout-minutes: 240
      - name: "Build Push dev UI"
        uses: docker/build-push-action@v3
        with:
          context: frontend
          file: frontend/Dockerfile.dev
          push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' }}
          tags: dzynetech/smart-ui-dev:${{ github.ref_name }}
        timeout-minutes: 240
      - name: "Build Push prod UI"
        uses: docker/build-push-action@v3
        with:
          context: frontend
          push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' }}
          tags: dzynetech/smart-ui:${{ github.ref_name }}
        timeout-minutes: 240
