name: Build Docker Images
on: 
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          TAG=${{ env.TAG }}
          PUSH=true
          if [[ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop' ]]; then
            PUSH=false
            TAG=temp
          fi
          echo "IS PR: $PUSH"
          echo "DOCKER TAG: $TAG"
          echo "PUSH=$PUSH" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: env.PUSH
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Build Push Node"
        uses: docker/build-push-action@v3
        with:
          context: node
          push: ${{ env.PUSH }}
          tags: dzynetech/smart-node:${{ env.TAG }}
        timeout-minutes: 240
      - name: "Build Push Ingest"
        uses: docker/build-push-action@v3
        with:
          context: python/ingest_server
          push: ${{ env.PUSH }}
          tags: dzynetech/smart-ingest:${{ env.TAG }}
        timeout-minutes: 240
      - name: "Build Push Geocode"
        uses: docker/build-push-action@v3
        with:
          context: python/geocode
          push: ${{ env.PUSH }}
          tags: dzynetech/smart-geocode:${{ env.TAG }}
        timeout-minutes: 240
      - name: "Build Push dev UI"
        uses: docker/build-push-action@v3
        with:
          context: frontend
          file: frontend/Dockerfile.dev
          push: ${{ env.PUSH }}
          tags: dzynetech/smart-ui-dev:${{ env.TAG }}
        timeout-minutes: 240
      - name: "Build Push prod UI"
        uses: docker/build-push-action@v3
        with:
          context: frontend
          push: ${{ env.PUSH }}
          tags: dzynetech/smart-ui:${{ env.TAG }}
        timeout-minutes: 240
