name: Publish Docker Image
on: 
  push:
    branches:
      - master
      - develop

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Build Push Node"
        uses: docker/build-push-action@v3
        with:
          file: node/Dockerfile
          push: true
          tags: bjubes/smart-node:${{ github.ref_name }}
        timeout-minutes: 240
