name: Check GraphQL Typescript Definitions
on: 
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  check-graphql-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Env
        run: |
          tee .env << END 
          DB_USER=postgres
          DB_PASSWORD=postgres
          DB_HOST=postgres
          END
      - name: Start Postgraphile
        run: docker-compose up -d postgraphile
      - name: Install graphql-codegen
        run: npm install
        working-directory: frontend/react
      - name: Generate TS Defs
        working-directory: frontend/react
        run: npm run generate
      - name: Detect changes
        run: git diff --exit-code
